### ISSUE TITLE
Add support for URLRepository / typesafe-ivy-releases

### ISSUE THREAD

**Issue by jsoref** [stripe/sbt-bazel#20]
`project/build.properties`:
```
sbt.version=1.2.8
```

```scala
[error] java.lang.RuntimeException: Unsupported resolver: URLRepository(typesafe-ivy-releases, Patterns(ivyPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false))
[error] 	at com.stripe.sbt.bazel.ZincLogic.$anonfun$allMavenResolvers$3(SbtBazelLogic.scala:136)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error] 	at scala.collection.immutable.List.map(List.scala:294)
[error] 	at com.stripe.sbt.bazel.ZincLogic.$anonfun$allMavenResolvers$2(SbtBazelLogic.scala:134)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
```

**Comment by andyscott** [comment]
Thanks for filing an issue!

We are no longer using or maintaining this plugin. 

I'll be archiving the repository shortly to ensure there's no confusion regarding support.
