### ISSUE TITLE
paiges error when performing bazelGenerate

### ISSUE THREAD

**Issue by ludflu** [stripe/sbt-bazel#8]
Thank you for your work on this project. It seems like just what I need.

Here's the problem I'm seeing:

When I execute`sbt bazelGenerate` I get the following error and stack trace:

```
[error] java.lang.NoSuchMethodError: org.typelevel.paiges.Doc.renderTrim(I)Ljava/lang/String;
[error]         at com.stripe.sbt.bazel.SbtBazel$.$anonfun$bazelGenerateMain$1(SbtBazelPlugin.scala:247)      
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)                                     
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)                           
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)                       
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)           
[error]         at sbt.Execute.work(Execute.scala:278)                                            
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)                               
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)                             
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                             
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)   
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                  
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)                                          
[error] java.lang.NoSuchMethodError: org.typelevel.paiges.Doc.renderTrim(I)Ljava/lang/String;
[error]         at com.stripe.sbt.bazel.SbtBazel$.$anonfun$bazelGenerateMain$1(SbtBazelPlugin.scala:247)      
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)                                     
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)                           
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)                       
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

Here's how my project is configured: 

- I've got and SBT multiproject with 13 sub-projects.
- I'm running sbt 1.2.1

I've set the scala rules at the top of my build.sbt:

`ThisBuild / bazelScalaRulesVersion := "0eab80ff0696d419aa54c2ab4b847ce9bdcbb379"`

I've added the flags to the root project:

```
lazy val root = (project in file("."))
  .aggregate(
    admin,
    `authorization-service`,
    api,
    `bf-akka-http`,
    core,
    jobs,
    notifications,
    `etl-consumer`,
    `etl-data-cli`,
    `uploads-consumer`,
    `workflow-consumer`,
    `model-publish`,
    `bf-akka`
  ).settings(commonSettings: _*)
  .settings(
    bazelWorkspaceGenerate := true,
    bazelBuildGenerate := false,
  )
```

and I've added the plugin to project/plugins.sbt:

`addSbtPlugin("com.stripe" %% "sbt-bazel" % "0.0.1")`

Thanks again!

**Comment by johnynek** [comment]
looks like you have an incompatible version of paiges on the classpath.

Can you look at your eviction warnings?

**Comment by ludflu** [comment]
looks like my evictions are a huge mess, but paiges isn't on the list. perhaps some shared dependency of paiges and sbt-bazel. I'll report back when I nail it down.

**Comment by ludflu** [comment]
closing since this is a dependency conflict problem, not an sbt-bazel problem

**Comment by ludflu** [comment]
For future travelers: the problem was cause by a different plugin with an incompatible version of paiges:

addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.6.0-RC4")

Once I commented that out, everything worked as expected
